#!/bin/bash
ssh-agent bash -c 'ssh-add ~/.ssh/backend-dist; git pull';
npm run backend; pm2 reload "ubexs API";
npm run frontend; pm2 reload "ubexs WWW";
npm run game-client; pm2 reload "ubexs Game Client";
