#!/bin/bash
ssh-agent bash -c 'ssh-add ~/.ssh/backend-dist; git pull';
npm run backend; pm2 reload "Ubexs API";
npm run frontend; pm2 reload "Ubexs WWW";
npm run game-client; pm2 reload "Ubexs Game Client";
